name: 'Github Runner Health Check'
description: 'Github Runner Health Check'
author: 'Santaev Pavel'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  token:
    description:
      'A github token. It is used to access list of runners for a repository'
    default: ${{ github.token }}
  labels:
    description: 'List of labels to look for runners'
    default: '{ "self-hosted" }'
outputs:
  number-all-runners:
    description: 'Number of all added runners for a repository'
  number-online-runners:
    description: 'Number of online runners for a repository'
  number-offline-runners:
    description: 'Number of offline runners for a repository'

runs:
  using: node20
  main: dist/index.js
